name: Generate Languages Card

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generar el languages.svg
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=agarcia-2024043&layout=compact&card_width=320&langs_count=5&theme=dracula&locale=en&hide_border=false
          path: output/languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publicar en la branch languages-output
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: languages-output
          keep_files: false
